import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiShadcnui,
  SiRedux,
  SiReactquery,
  SiGit,
  SiGithub,
  SiFramer,
  SiZod,
} from 'react-icons/si';
import { TbBox } from 'react-icons/tb';
import type { TechItem } from './types';

export const TECH_STACK: TechItem[] = [
  {
    id: 'html',
    system: 'SYS.01',
    name: 'HTML5',
    category: 'Markup Language',
    icon: SiHtml5,
    level: 92,
  },
  {
    id: 'css',
    system: 'SYS.02',
    name: 'CSS3',
    category: 'Styling Language',
    icon: SiCss,
    level: 90,
  },
  {
    id: 'javascript',
    system: 'SYS.03',
    name: 'JavaScript',
    category: 'Programming Language',
    icon: SiJavascript,
    level: 88,
  },
  {
    id: 'typescript',
    system: 'SYS.04',
    name: 'TypeScript',
    category: 'Typed JavaScript',
    icon: SiTypescript,
    level: 90,
  },
  {
    id: 'react',
    system: 'SYS.05',
    name: 'React',
    category: 'Frontend Library',
    icon: SiReact,
    level: 88,
  },
  {
    id: 'nextjs',
    system: 'SYS.06',
    name: 'Next.js',
    category: 'React Framework',
    icon: SiNextdotjs,
    level: 87,
  },
  {
    id: 'tailwind',
    system: 'SYS.07',
    name: 'Tailwind CSS',
    category: 'Utility CSS',
    icon: SiTailwindcss,
    level: 87,
  },
  {
    id: 'shadcn',
    system: 'SYS.08',
    name: 'Shadcn UI',
    category: 'Component Library',
    icon: SiShadcnui,
    level: 85,
  },
  {
    id: 'redux',
    system: 'SYS.09',
    name: 'Redux Toolkit',
    category: 'State Management',
    icon: SiRedux,
    level: 89,
  },
  {
    id: 'tanstack',
    system: 'SYS.10',
    name: 'TanStack Query',
    category: 'Server State',
    icon: SiReactquery,
    level: 85,
  },
  {
    id: 'git',
    system: 'SYS.11',
    name: 'Git',
    category: 'Version Control',
    icon: SiGit,
    level: 84,
  },
  {
    id: 'github',
    system: 'SYS.12',
    name: 'GitHub',
    category: 'Source Control',
    icon: SiGithub,
    level: 89,
  },
  {
    id: 'framer',
    system: 'SYS.13',
    name: 'Framer Motion',
    category: 'Animation Library',
    icon: SiFramer,
    level: 88,
  },
  {
    id: 'zod',
    system: 'SYS.14',
    name: 'Zod',
    category: 'Schema Validation',
    icon: SiZod,
    level: 88,
  },
  {
    id: 'zustand',
    system: 'SYS.15',
    name: 'Zustand',
    category: 'State Library',
    icon: TbBox,
    level: 86,
  },
];