// Education Animation
export const EDUCATION_ANIMATION = {
  INITIAL_Y: 40,
  DURATION: 0.8,
  VIEWPORT_AMOUNT: 0.2,
  HOVER_SCALE: 1.04,
  HOVER_ROTATE: 3,
  HOVER_Y: 2,
  SPRING_STIFFNESS: 300,
  SPRING_DAMPING: 20,
  CERTIFICATE_ICON_SIZE: 28,
  CERTIFICATE_ICON_STROKE: 1.5,
  ARROW_ICON_SIZE: 16,
  ARROW_ICON_STROKE: 1.7,
  CHECK_ICON_SIZE: 12,
  CHECK_ICON_STROKE: 1.8,
} as const;

// Education Layout
export const EDUCATION_LAYOUT = {
  MOBILE_PADDING: 7,
  TABLET_PADDING: 10,
  DESKTOP_PADDING: 12,
  CREDENTIAL_ICON_TOP_SPACING: 20,
  CREDENTIAL_LABEL_TOP_SPACING: 8,
  CREDENTIAL_CTA_TOP_SPACING: 10,
  PROGRAM_CONTENT_TOP_SPACING: 16,
  PROGRAM_DESCRIPTION_TOP_SPACING: 7,
  PROGRAM_FOCUS_TOP_SPACING: 12,
  PROGRAM_BOTTOM_TOP_SPACING: 12,
  SKILL_GAP: 2,
  SKILL_HORIZONTAL_PADDING: 3.5,
  SKILL_VERTICAL_PADDING: 2,
  BOTTOM_LINE_WIDTH: 8,
  BOTTOM_LINE_HOVER_WIDTH: 14,
  BOTTOM_LINE_GAP: 3,
} as const;

// Education Visual
export const EDUCATION_VISUAL = {
  GLOW_SIZE: 384,
  GLOW_OFFSET: -160,
  GLOW_BLUR: 100,
  SECONDARY_GLOW_SIZE: 320,
  SECONDARY_GLOW_OFFSET: -128,
  TOP_ACCENT_HEIGHT: 1,
  BORDER_OPACITY: '0.08',
  SURFACE_OPACITY: '0.025',
  GLOW_OPACITY: '0.06',
  SECONDARY_GLOW_OPACITY: '0.035',
  ICON_BORDER_OPACITY: '0.2',
  ICON_BACKGROUND_OPACITY: '0.06',
  CTA_BORDER_OPACITY: '0.1',
  CTA_BACKGROUND_OPACITY: '0.025',
  SKILL_BORDER_OPACITY: '0.07',
  SKILL_BACKGROUND_OPACITY: '0.02',
  TOP_ACCENT_OPACITY: '0.6',
  TEXT_SECONDARY_OPACITY: '0.65',
  TEXT_MUTED_OPACITY: '0.4',
  TEXT_SUBTLE_OPACITY: '0.25',
  TEXT_FAINT_OPACITY: '0.2',
} as const;

// Education Header Animation
export const EDUCATION_HEADER_ANIMATION = {
  SECTION_INITIAL_X: -20,
  SECTION_DURATION: 0.7,
  SECTION_VIEWPORT_AMOUNT: 0.4,
  LABEL_INITIAL_Y: 15,
  LABEL_DURATION: 0.6,
  LABEL_VIEWPORT_AMOUNT: 0.4,
  TITLE_DELAY: 0.05,
  TITLE_STAGGER: 0.06,
  TITLE_DURATION: 0.65,
  TITLE_Y: 35,
  TITLE_BLUR: 8,
  DESCRIPTION_INITIAL_Y: 20,
  DESCRIPTION_DURATION: 0.7,
  DESCRIPTION_DELAY: 0.35,
  DESCRIPTION_VIEWPORT_AMOUNT: 0.3,
} as const;

// Education Header Layout
export const EDUCATION_HEADER_LAYOUT = {
  BOTTOM_MARGIN: 64,
  BOTTOM_MARGIN_MD: 96,
  GRID_GAP: 8,
  GRID_COLUMN_WIDTH: 180,
  GRID_GAP_MD: 12,
  SECTION_LINE_WIDTH: 8,
  SECTION_GAP: 3,
  SECTION_TOP_PADDING: 2,
  LABEL_BOTTOM_MARGIN: 5,
  DESCRIPTION_TOP_MARGIN: 7,
} as const;

// Education Easing
export const EDUCATION_EASE = [0.22, 1, 0.36, 1] as const;
